### ISSUE TITLE
Calibration does not save

### ISSUE THREAD

**Issue by ranum18** [mangdangroboticsclub/mini_pupper_bsp#51]
### Reproduction steps

Step1: flash the up pre-built image
Step2: calibrate your robot
There is no desktop in the pre-built image, you can use your Laptop with Ubuntu Desktop to run the follow commands,
run on your Laptop with Ubuntu Desktop
$ssh -X ubuntu@IP # IP means your robot IP address, such as, ssh -X ubuntu@192.168.5.109
$calibrate  # this command will display a GUI calibration tool

Step3: follow the ros guide to try
For mini pupper v1, there is calibration section in the following GitHub repo
https://github.com/mangdangroboticsclub/mini_pupper_bsp

### Actual results

<img width="443" alt="image" src="https://github.com/user-attachments/assets/e15a6cf0-3c0c-4d17-9de3-4e3392ba26a7">

### Expected results

Calibration should save

### Version

Mini Pupper

### Relevant log output

```shell
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/usr/local/lib/python3.10/dist-packages/MangDang/mini_pupper/calibrate_tool.py", line 235, in updateButtonEvent
    self.writeCalibrationFile()
  File "/usr/local/lib/python3.10/dist-packages/MangDang/mini_pupper/calibrate_tool.py", line 178, in writeCalibrationFile
    nvram.write(data)
  File "/usr/local/lib/python3.10/dist-packages/MangDang/mini_pupper/nvram.py", line 7, in write
    with open(ServoCalibrationFilePath, 'wb') as fd:
FileNotFoundError: [Errno 2] No such file or directory: '/sys/bus/nvmem/devices/3-00501/nvmem'
^CTraceback (most recent call last):
  File "/usr/local/bin/calibrate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/MangDang/mini_pupper/calibrate_tool.py", line 321, in main
    MainWindow.runMainWindow()
  File "/usr/local/lib/python3.10/dist-packages/MangDang/mini_pupper/calibrate_tool.py", line 281, in runMainWindow
    self.MainWindow.mainloop()
  File "/usr/lib/python3.10/tkinter/__init__.py", line 1458, in mainloop
    self.tk.mainloop(n)
KeyboardInterrupt

```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mangdangroboticsclub** [comment]
Improper operation, not a bug
